<a href="https://colab.research.google.com/github/AhHosny/CIT690E-DL-Course/blob/master/TUT_1_Basic_Pytorch_Tensor_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is PyTorch

[PyTorch](https://pytorch.org/) is an open-source machine learning library developed by Facebook that supports multiple languages, such as Python and C++ PyTorch is among the most famous and widely used libraries for machine learning in the world. Many software tools and products are built on top of PyTorch, including Tesla Autopilot, Uber’s Pyro, and HuggingFace’s Transformers.

## What is a PyTorch tensor

In short, a PyTorch<font color='red'>`tensor`</font> is an n-dimensional array that is the same as a NumPy array or TensorFlow tensor. You can consider a <font color='red'>`rank 0`</font> tensor as a scalar, a <font color='red'>`rank 1`</font> tensor as a vector, and a <font color='red'>`rank 2`</font> tensor as a matrix. For higher-dimensional, they are rank <font color='red'>`n`</font> tensor. This difference between the ranks is shown in the figure below.

![tensor_1](https://d3i71xaburhd42.cloudfront.net/82750a1533ca30a705d3325290ee8de471073773/3-Figure3-1.png)



Tensors are just higher-dimensional matrices.
![tensor_2](https://drek4537l1klr.cloudfront.net/stevens2/v-12/Figures/p1ch3_tensors.png)

**Make sure to check [this version](http://karlstratos.com/drawings/linear_dogs.jpg) out!**

First things first, let's import the PyTorch module. We'll also add Python's math module to facilitate some of the examples.

In [1]:
import torch
import math

## Creating Tensors

### 1. Empty Tensor

The simplest way to create a tensor is with the <font color='red'>`torch.empty()`</font> call:

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[5.9400e+25, 3.0952e-41, 3.3631e-44, 0.0000e+00],
        [       nan, 3.0952e-41, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


Let's unpack what we just did:

* We created a tensor using one of the numerous factory methods attached to the <font color='red'>`torch`</font> module.
* The tensor itself is 2-dimensional, having 3 rows and 4 columns.
* The type of the object returned is <font color='red'>`torch.Tensor`</font>, which is an alias for <font color='red'>`torch.FloatTensor`</font>; by default, PyTorch tensors are populated with 32-bit floating point numbers. (More on data types below.)
* You will probably see some random-looking values when printing your tensor. The <font color='red'>`torch.empty()`</font> call allocates memory for the tensor, but does not initialize it with any values - so what you're seeing is whatever was in memory at the time of allocation.

### 2. Creating a tensor from a list

Creating a tensor from a list or a nested list is easy. First, we need to import the <font color='red'>`torch`</font> library and call the  <font color='red'>`tensor`</font> function.

In [3]:
a = torch.tensor([1, 2, 3])
print(a)

tensor([1, 2, 3])


In [4]:
b = torch.tensor([[1], [2], [3]])
print(b)

tensor([[1],
        [2],
        [3]])


The <font color='red'>```tensor```</font> function supports different types, which will be discussed in a later lesson. In this example, we use the default type,<font color='red'>```torch.int64```</font>.

### 3. Creating a tensor from a NumPy array

If we have a NumPy array and want to convert it to a PyTorch <font color='red'>`tensor`</font>, we just pass it to the tensor function as an argument, as shown below.

In [5]:
import numpy as np

na = np.array([1, 2, 3])
a = torch.tensor(na)

We can also use the <font color='red'>`from_numpy`</font> function to convert a NumPy array to a PyTorch tensor. You just have to pass the NumPy array object as an argument.

In [6]:
b = torch.from_numpy(na)

#### 4. Creating special tensors

**PyTorch** provides some useful functions to create special tensors, such as the identity tensor and tensors having all zeros or ones.
*  <font color='red'>`eye()`</font>: Creates an identity tensor with an integer.
*  <font color='red'>`zeros()`</font>: Creates a tensor with all zeros. The parameter could be an integer or a tuple that defines the shape of the tensor.
*  <font color='red'>`ones()`</font>: Creates a tensor with all ones like ones. The parameter could be an integer or a tuple that defines the shape of the tensor.

In [7]:
# Create a identity tensor with 3*3 shape.
eys = torch.eye(3)
print(eys)

# Create a tensor with 2*2 shape whose values are all 1.
ones = torch.ones((2, 2))
print(ones)

# Create a tensor with 3*3 shape whose values are all 0.
zeros = torch.zeros((3, 3))
print(zeros)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### 5. Creating a random tensor

**PyTorch** provides some useful functions to create a tensor with a random value.

*  <font color='red'>`rand()`</font>: It creates a tensor filled with random numbers from a uniform distribution. The parameter is a sequence of integers defining the shape of the output tensor. It can be a variable number of arguments or a collection like a <font color='red'>`list`</font> or a <font color='red'>`tuple`</font>.
*  <font color='red'>`randn()`</font>: It creates a tensor filled with random numbers from a normal distribution with mean 0 and variance 1. The parameter is the same as the <font color='red'>`rand()`</font>.
*  <font color='red'>`randint()`</font>: Unlike the functions above, this function creates a <font color='red'>`tensor`</font> with integer values with <font color='red'>`low`</font>, <font color='red'>`high`</font> and <font color='red'>`size`</font> parameters. <font color='red'>`low`</font> means the lowest value, it’s optional and the default value is 0. <font color='red'>`high`</font> means the highest value, and <font color='red'>`size`</font> is a tuple that defines the shape of the tensor.

In [8]:
# Create a tensor with 1*10 shape with random value between 0 and 1
r0 = torch.rand(10)
print(r0)
print("************************************************")
# Create a tensor with 10*1 shape with random value between 0 and 1
r1 = torch.rand((10, 1))
print(r1)
print("************************************************")
# Create a tensor with 2*2 shape with random value between 0 and 1
r2 = torch.rand((2, 2))
print(r2)
print("************************************************")
# Create a tensor with 2*2 shape with random value from a normal distribution.
r3 = torch.randn((2,2))
print(r3)
print("************************************************")
# Create an integer type tensor with 3*3 shape with random value between 0 and 10.
r4 = torch.randint(high=10, size=(3, 3))
print(r4)
print("************************************************")
# Create an integer type tensor with 3*3 shape with random value between 5 and 10.
r5 = torch.randint(low=5, high=10, size=(3, 3))
print(r5)

tensor([0.5738, 0.4545, 0.4875, 0.0501, 0.0176, 0.0471, 0.5054, 0.9491, 0.3337,
        0.5506])
************************************************
tensor([[0.3863],
        [0.3577],
        [0.5707],
        [0.4629],
        [0.8836],
        [0.8632],
        [0.7276],
        [0.5459],
        [0.1114],
        [0.6585]])
************************************************
tensor([[0.4633, 0.0426],
        [0.2548, 0.3268]])
************************************************
tensor([[ 0.0998, -0.3802],
        [ 0.1119,  0.2327]])
************************************************
tensor([[2, 8, 5],
        [8, 4, 9],
        [3, 7, 7]])
************************************************
tensor([[9, 8, 5],
        [6, 7, 9],
        [5, 6, 6]])


**Random Tensors and Seeding**

Speaking of the random tensor, did you notice the call to <font color='red'>`torch.manual_seed()`</font> immediately preceding it? Initializing tensors, such as a model's learning weights, with random values is common but there are times - especially in research settings - where you'll want some assurance of the reproducibility of your results. Manually setting your random number generator's seed is the way to do this. Let's look more closely:

In [9]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


### 6. Creating a range tensor

PyTorch also provides a function <font color='red'>`arange`</font> that generates values in <font color='red'>`[start; end)`</font>, like NumPy.

**Tensor Shapes**

Often, when you're performing operations on two or more tensors, they will need to be of the same *shape* - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the <font color='red'>`torch.*_like()`</font> methods:

In [10]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[5.9402e+25, 3.0952e-41, 3.3631e-44],
         [0.0000e+00,        nan, 0.0000e+00]],

        [[4.4721e+21, 1.5956e+25, 4.7399e+16],
         [3.7293e-08, 1.4838e-41, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[5.9399e+25, 3.0952e-41, 3.3631e-44],
         [0.0000e+00,        nan, 5.9382e-01]],

        [[1.1578e+27, 1.1362e+30, 7.1547e+22],
         [4.5828e+30, 1.2121e+04, 7.1846e+22]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [11]:
a = torch.arange(1, 10)
print(a)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


## Tensor Metadate

### 1. Getting type from <font color='red'>`dtype`</font>

The <font color='red'>`dtype`</font> attribute of a PyTorch tensor can be used to get its type information.

The code below creates a tensor with the float type and prints the type information from dtype. 

In [12]:
a = torch.tensor([1, 2, 3], dtype=torch.float)
print(a.dtype)

torch.float32


### 2. Getting size from <font color='red'>`shape`</font> and <font color='red'>`size()`</font>
PyTorch provides two ways to get the tensor size; these are <font color='red'>`shape`</font>, an attribute, and <font color='red'>`size()`</font>, which is a function.

In [13]:
a = torch.ones((3, 4))
print(a.shape)
print(a.size())

torch.Size([3, 4])
torch.Size([3, 4])


### 3. Getting the number of dim
As shown in the code below, the number of dimensions of a tensor in Pytorch can be obtained using the attribute <font color='red'>`ndim`</font> or using the function <font color='red'>`dim()`</font> or its alias <font color='red'>`ndimension()`</font>.

In [14]:
a = torch.ones((3, 4, 6))
print(a.ndim)
print(a.dim())

3
3


### 4. Getting the number of elements

PyTorch provides two ways to get the number of elements of a tensor, <font color='red'>`nelement()`</font> and <font color='red'>`numel()`</font>. Both of them are functions.

In [15]:
a = torch.ones((3, 4, 6))
print(a.numel())

72


## Tensor Types

### Why tensor type is important#
Similar to other frameworks, PyTorch too defines its types for its tensor. Some frequently used types are listed in the table below.

| Data Type  | dtype | CPU tensor | GPU tensor |
| --- | --- | --- |---|
| 32-bit floating point | torch.float32/torch.float | torch.FloatTensor | torch.cuda.FloatTensor |
|64-bit floating point|torch.float64/torch.double|torch.DoubleTensor|torch.cuda.DoubleTensor|
|8-bit integer (signed)|torch.int16|torch.ShortTensor|torch.cuda.ShortTensor|
|boolean|torch.bool|torch.BoolTensor|torch.cuda.BoolTensor|

The tensor type is vital. There are two main reasons.

*  It affects speed and memory usage because the GPU has video memory limitations. More bits type takes up more memory and requires more computing resources. For example, a matrix <font color='red'>`A`</font> with size 1000x1000. If the <font color='red'>`dtype`</font> is <font color='red'>`torch.float32`</font>, this matrix would consume about **3.81MB GPU memory** (1000x1000x4bytes, each <font color='red'>`float32`</font> uses 4 bytes.). If the <font color='red'>`dtype`</font> is <font color='red'>`torch.double`</font>, this matrix would consume about **7.62MB GPU memory** (1000x1000x8bytes, each <font color='red'>`double`</font> uses 8 bytes.).

* Some APIs have strong requirements for types. For example, when you train a model about a classification task, you need to calculate some metrics. The tensor type of input of some API requires the torch.long type. You could check this [example](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html).



### 1. Creating tensors from specified APIs

**PyTorch** provides some useful functions to create tensors with the specified type.

* <font color='red'>`FloatTensor`</font>: This function creates tensors with <font color='red'>`torch.float32`</font> type.
* <font color='red'>`IntTensor`</font>: This function creates tensors with <font color='red'>`torch.int32`</font> type.
* <font color='red'>`DoubleTensor`</font>: This function creates tensors with <font color='red'>`torch.float64`</font> type.
* <font color='red'>`LongTensor`</font>: This function creates tensors with <font color='red'>`torch.long`</font> type.


In [16]:
d = torch.FloatTensor([1, 2, 3])
e = torch.IntTensor([1, 2, 3])

### 2. Casting tensors into different types

The Tensor class has the method <font color='red'>`to()`</font>, which can cast tensors into different types. To cast a tensor, call its <font color='red'>`to()`</font> method and pass the dtype as the argument, as shown in the code below.

In [17]:
b = torch.tensor([1, 2, 3], dtype=torch.float)
print("The dtype for b is {}".format(b.dtype))

c = b.to(dtype=torch.int64)
print("The dtype for c is {}".format(c.dtype))

The dtype for b is torch.float32
The dtype for c is torch.int64


**Notice**: The <font color='red'>`to()`</font> cast is not an in-place operation, which means the original tensor wouldn’t be modified. It would return a new tensor with the new type.

## Selecting Elements from a Tensor

### 1. Selecting tensor with index

If you are already familiar with the NumPy array, you can use the same methods to select tensors by <font color='red'>`[]`</font> operations.

Take a 2-dimensional tensor as an example. Let’s consider it as a matrix.

* <font color='red'>`tensor[2, 3]`</font>: Get only one value.
* <font color='red'>`tensor[:, 1]`</font>: Get the second column from the tensor.
* <font color='red'>`tensor[1, :]`</font>: Get the second row from the tensor.
For higher-dimensional tensors, the operations are the same. Such as <font color='red'>`tensor[:, 2, :]`</font>.

In [18]:
a = torch.arange(1, 10).reshape((3, 3))
# The output
# tensor([[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]])
print("The original tensor")
print(a)

print("Select only one element")
print(a[1,1])

print("Select the second column")
print(a[:, 1])

print("Select the second row.")
print(a[1, :])

The original tensor
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Select only one element
tensor(5)
Select the second column
tensor([2, 5, 8])
Select the second row.
tensor([4, 5, 6])


### 2. Selelcting tensor with <font color='red'>`index_select`</font>

**PyTorch** provides a function <font color='red'>`index_select`</font> which enables us to select some elements from a tensor with indices.

At first, we need to create a tensor (<font color='red'>`Long`</font> type) that indicates the indices we want to select. Since we want to use <font color='red'>`index`</font> to locate the element in a tensor, this tensor must be of <font color='red'>`Long`</font> type.

<font color='red'>`index_select`</font> requires the following parameters:

* The first parameter is the tensor we want to select.
* <font color='red'>`dim`</font>: It indicates the dimension in which we index. In this example, the tensor is a 2-dimensions tensor. <font color='red'>`dim=0`</font> means the row, <font color='red'>`dim=1`</font> means the column.
* <font color='red'>`index`</font>: The 1-D tensor containing the indices to index.

In [19]:
a = torch.arange(1, 10).reshape((3, 3))

indices = torch.LongTensor([0, 2])
result = torch.index_select(a, dim=0, index=indices)
print(result)

tensor([[1, 2, 3],
        [7, 8, 9]])


### 3. Selecting tensor with a mask

The mask tensor is <font color='red'>`BoolTensor`</font>, which identifies which elements are chosen. The <font color='red'>`shape`</font> of the mask tensor and the original tensor doesn’t need to match, but they must be broadcastable.

In short, PyTorch enables us to pass a tensor of Boolean type to <font color='red'>`masked_select`</font>, which selects desired elements from another tensor.

In [20]:
a = torch.arange(1, 10).reshape((3, 3))

mask = torch.BoolTensor([[True, False, True],
                        [False, False, True],
                        [True, False, False]])
print("The mask tensor is: \n{}".format(mask))
print("The original tensor is: \n{}".format(a))
result = torch.masked_select(a, mask)
print("The result is {}".format(result))

The mask tensor is: 
tensor([[ True, False,  True],
        [False, False,  True],
        [ True, False, False]])
The original tensor is: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The result is tensor([1, 3, 6, 7])


## Changing the Shape of a Tensor

### 1. Reshaping a tensor

If you already have one tensor, but the <font color='red'>`shape`</font> is not what you expect, <font color='red'>`shape()`</font> is the function you need. It allows us to create a tensor with the same data and number of original tensor elements.

<font color='red'>`shape()`</font> requires two parameters. The first parameter **input** is the tensor to be reshaped. The second parameter is the <font color='red'>`shape`</font> which is a tuple of int, the new shape.

In [21]:
a = torch.arange(1, 9)
print("The original tensor\n.")
print(a)

b = torch.reshape(a, (2, 4))
print("The reshape tensor with shape (2, 4)\n")
print(b)

c = torch.reshape(a, (2, -1))
print("The reshape tensor with shape (2, -1)\n")
print(c)

The original tensor
.
tensor([1, 2, 3, 4, 5, 6, 7, 8])
The reshape tensor with shape (2, 4)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
The reshape tensor with shape (2, -1)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


### 2. Squeezing a tensor

Sometimes, the size of some dimensions of a tensor is 1. For example, a tensor’s shape is (10, 2, 1, 5), and we want to remove the third dimension. <font color='red'>`squeeze()`</font> is the function we need.

* We can’t squeeze a dimension if the size is greater than 1.
* We can squeeze multiple dimensions simultaneously in one function call. But, it would squeeze all.

<font color='red'>`squeeze()`</font> has two parameters:

* <font color='red'>`input`</font>: The tensor we want to perform squeeze on.
* <font color='red'>`dim`</font>: The dimension we want to perform squeeze on. It’s optional.

In [22]:
a = torch.ones((3, 1, 2))
print("The original shape of a is {}".format(a.shape))
print("The original a tensor is {}".format(a))

a = torch.squeeze(a, dim=1)
print("The new shape of a is {}".format(a.shape))
print("The new tensor is {}".format(a))

b = torch.ones((3,1,2,1,2))
print("The original shape of a is {}".format(b.shape))
print("The original b tensor is {}".format(b))

b = torch.squeeze(b)
print("The new shape of a is {}".format(b.shape))
print("The new tensor is {}".format(b))

The original shape of a is torch.Size([3, 1, 2])
The original a tensor is tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])
The new shape of a is torch.Size([3, 2])
The new tensor is tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
The original shape of a is torch.Size([3, 1, 2, 1, 2])
The original b tensor is tensor([[[[[1., 1.]],

          [[1., 1.]]]],



        [[[[1., 1.]],

          [[1., 1.]]]],



        [[[[1., 1.]],

          [[1., 1.]]]]])
The new shape of a is torch.Size([3, 2, 2])
The new tensor is tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


### 3. Un-squeezing a tensor#
Since we can remove one dim from a tensor, we may want to add one more dim to a tensor as well. For example, a tensor’s shape is (3, 3), you could add one dim like (3, 1, 3) by <font color='red'>`unsqueeze()`</font>.

* <font color='red'>`dim`</font>: This parameter indicates the index at which to insert the dimension.

In [23]:
a = torch.ones((3, 3))
print("The original shape of a is {}".format(a.shape))
print("The original a tensor is {}".format(a))

a = torch.unsqueeze(a, dim=1)
print("The new shape of a is {}".format(a.shape))
print("The new tensor is {}".format(a))

The original shape of a is torch.Size([3, 3])
The original a tensor is tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
The new shape of a is torch.Size([3, 1, 3])
The new tensor is tensor([[[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]])


### 4. Transposing a tensor

Transposing a tensor is quite simple in **PyTorch**, just call the <font color='red'>`transpose()`</font>. This function requires two parameters, <font color='red'>`dim0`</font>, and <font color='red'>`dim1`</font>, which indicate the first and the second dim to be transposed.

In [24]:
a = torch.ones((2, 4))
print("The original shape of a is {}".format(a.shape))
print("The original tensor a is {}".format(a))

a = torch.transpose(a, 0, 1)
print("The new shape of a is {}".format(a.shape))
print("The new tensor a is {}".format(a))

b = torch.ones((2, 4, 2))
print("The original shape of b is {}".format(b.shape))
print("The original tensor b is {}".format(b))

b = torch.transpose(b, 1, 2)
print("The new shape of b is {}".format(b.shape))
print("The new tensor b is {}".format(b))

The original shape of a is torch.Size([2, 4])
The original tensor a is tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
The new shape of a is torch.Size([4, 2])
The new tensor a is tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
The original shape of b is torch.Size([2, 4, 2])
The original tensor b is tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
The new shape of b is torch.Size([2, 2, 4])
The new tensor b is tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


## Concatenating tensors

### 1. Concatenate the tensors

<font color='red'>`torch.cat()`</font> can concatenate a sequence of tensors in a given dimension. All tensors should have the same shape. Below are the important parameters.

* <font color='red'>`tensors`</font>: A list of tensors must have the same shape.
* <font color='red'>`dim`</font>: The dimension over which the tensors are concatenated. Take 2D tensors as an example, <font color='red'>`dim=0`</font> means the operation would be performed row-wise. <font color='red'>`dim=1`</font> means the operation would be performed column-wise.

In [25]:
a = torch.randn((3, 3))
print("The original tesnor a is\n {}".format(a))
result = torch.cat((a, a), dim=0)
print("The shape of result is {}".format(result.shape))
print("The new tensor is\n {}".format(result))

b = torch.randn((3, 3))
print("The original tesnor b is\n {}".format(b))
result = torch.cat((b, b), dim=1)
print("The shape of result is {}".format(result.shape))
print("The new tensor is\n {}".format(result))

The original tesnor a is
 tensor([[ 0.3645,  0.1179, -0.3338],
        [ 1.2409, -1.2293, -0.4904],
        [ 0.1263, -0.0732,  1.0363]])
The shape of result is torch.Size([6, 3])
The new tensor is
 tensor([[ 0.3645,  0.1179, -0.3338],
        [ 1.2409, -1.2293, -0.4904],
        [ 0.1263, -0.0732,  1.0363],
        [ 0.3645,  0.1179, -0.3338],
        [ 1.2409, -1.2293, -0.4904],
        [ 0.1263, -0.0732,  1.0363]])
The original tesnor b is
 tensor([[-0.5292,  0.6205,  1.7128],
        [-1.2221, -1.1406,  1.1263],
        [-1.7528, -0.5989, -2.3606]])
The shape of result is torch.Size([3, 6])
The new tensor is
 tensor([[-0.5292,  0.6205,  1.7128, -0.5292,  0.6205,  1.7128],
        [-1.2221, -1.1406,  1.1263, -1.2221, -1.1406,  1.1263],
        [-1.7528, -0.5989, -2.3606, -1.7528, -0.5989, -2.3606]])


### 2. Stacking the tensors

<font color='red'>`torch.cat()`</font> concatenates the given sequence of <font color='red'>`seq`</font> tensors in the <font color='red'>`given dimension`</font>.

<font color='red'>`torch.stack()`</font> is similar to <font color='red'>`torch.cat()`</font>, <font color='red'>`torch.stack()`</font> concatenates the sequence of tensors along a new dimension.

For example, there are two tensors with the shape (3, 4). We stack these two tensors with <font color='red'>`dim=1`</font>, then the shape of the return value would be (3, 2, 4).

In [26]:
a = torch.randn((2, 2))
b = torch.randn((2, 2))
print("The original tesnor a is\n {}".format(a))
print("The original tesnor b is\n {}".format(b))
result = torch.stack((a, b), dim=1)
print("The shape of result is {}".format(result.shape))
print("The new tensor is\n {}".format(result))

The original tesnor a is
 tensor([[ 0.0695, -0.4278],
        [-0.4861, -0.7959]])
The original tesnor b is
 tensor([[-0.5204, -0.7523],
        [ 2.2930,  0.9971]])
The shape of result is torch.Size([2, 2, 2])
The new tensor is
 tensor([[[ 0.0695, -0.4278],
         [-0.5204, -0.7523]],

        [[-0.4861, -0.7959],
         [ 2.2930,  0.9971]]])


## Element-wise Mathematical Operations on Tensors

### Math operation with scalar

If you have used the NumPy array before, you may already know that we can perform a math operation between a NumPy array and a scalar. PyTorch tensor supports almost the same operations. In PyTorch, we perform it in two ways:

* The operators, such as <font color='red'>`+`</font>, <font color='red'>`-`</font>, and <font color='red'>`*`</font>.
* The functions, such as <font color='red'>`add`</font>, <font color='red'>`sub`</font>, and <font color='red'>`mul`</font>.

In [27]:
a = torch.tensor([1,2,3])
b = a + 3
b = a.add(3)

PyTorch supports most of the math functions under the native Python <font color='red'>`math`</font> module. You could find a complete list from the [official site](https://pytorch.org/docs/stable/torch.html#pointwise-ops).

In [28]:
a = torch.tensor([1,2,3])
print("The original tensor a is {}".format(a))

b = a + 3
print("Th new tensor b is {}".format(b))

b = a.add(3)
print("Th new tensor b is {}".format(b))

print("The tensor a is still {}".format(a))

a.add_(3)
print("The new tensor a is {}".format(a))

The original tensor a is tensor([1, 2, 3])
Th new tensor b is tensor([4, 5, 6])
Th new tensor b is tensor([4, 5, 6])
The tensor a is still tensor([1, 2, 3])
The new tensor a is tensor([4, 5, 6])


### 2. Math operation between tensors

Since the tensors could be performed with a single scalar, it also works between two tensors with the same shape. It even works for 2D or higher ranked tensors. These operations are element-wise, which means these operations happen between two pairs of corresponding elements of these two tensors.

In [29]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 4, 6])

c = a * b
print("The multiple between a an b is {}".format(c))

c = a.mul(b)
print("The multiple between a an b is {}".format(c))

e = torch.tensor([[1, 2], [3, 4]])
f = torch.tensor([[2, 2], [2, 2]])

g = e*f 
print("The multiple between e an f is {}".format(g))

The multiple between a an b is tensor([ 2,  8, 18])
The multiple between a an b is tensor([ 2,  8, 18])
The multiple between e an f is tensor([[2, 4],
        [6, 8]])


### 3. Altering Tensors in Place

Most binary operations on tensors will return a third, new tensor. When we say <font color='red'>`c = a * b`</font> (where <font color='red'>`a`</font> and <font color='red'>`b`</font> are tensors), the new tensor <font color='red'>`c`</font> will occupy a region of memory distinct from the other tensors.

There are times, though, that you may wish to alter a tensor in place - for example, if you're doing an element-wise computation where you can discard intermediate values. For this, most of the math functions have a version with an appended underscore (<font color='red'>`_`</font>) that will alter a tensor in place.

In [30]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


For arithmetic operations, there are functions that behave similarly:

In [31]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9883, 0.4762],
        [0.7242, 0.0776]])

After adding:
tensor([[1.9883, 1.4762],
        [1.7242, 1.0776]])
tensor([[1.9883, 1.4762],
        [1.7242, 1.0776]])
tensor([[0.9883, 0.4762],
        [0.7242, 0.0776]])

After multiplying
tensor([[0.9768, 0.2268],
        [0.5245, 0.0060]])
tensor([[0.9768, 0.2268],
        [0.5245, 0.0060]])


## Reduction and Comparison

### 1. Reduction functions

The reduction operator is a type of operator that is commonly used in parallel programming to reduce the elements of an array into a single result. For example, we can calculate the mean value of a float array is a reduction operation.

**PyTorch** provides some useful functions for reduction. If you have used NumPy before, you may notice the usage and name are the same. Below are some important functions, they all have a parameter <font color='red'>`dim`</font>, which indicates on which dimension the summarization is performed. The default value for <font color='red'>`dim`</font> is 0.

|Function | Name | Purpose|
|---|---|---|
|mean|	Get the mean value of the tensor in the given dimension.|
|sum|	Sum the values of the tensor over the given dimension.|
|median|	Get the median value of tensor in the given dimension.|
|std|	Compute the standard deviation of the tensor over the given dimension.|
|prod|	Product the values of the tensor over the given dimension.|
|cumsum|	Cumulative sum of values of the tensor over the given dimension.|

In [32]:
a = torch.randn((3,4))
print("The original tensor is \n {}".format(a))

print("="*30)
b = torch.mean(a, dim=1)
print("The mean value of dim=1 \n {}".format(b))

print("="*30)
c = torch.sum(a, dim=0)
print("The sum value of dim=0 \n {}".format(c))

The original tensor is 
 tensor([[ 0.2359,  0.7787, -0.1732, -0.1074],
        [ 1.9456,  0.4525,  0.1014,  0.3339],
        [ 1.6279,  1.0423, -0.6320,  1.4610]])
The mean value of dim=1 
 tensor([0.1835, 0.7084, 0.8748])
The sum value of dim=0 
 tensor([ 3.8094,  2.2735, -0.7038,  1.6875])


### 2. Comparison functions

**PyTorch** allows us to compare a tensor with another tensor or a scalar, element-wise. The return value is a <font color='red'>`Boolean`</font> tensor that contains a <font color='red'>`True`</font> at each location where the comparison is true.

For these functions in the list, they require two parameters.

* **inputs**: The tensor to compare.
* **other**: The tensor or value to compare. If it’s a tensor, then the comparison is performed element-wise.

|Function	| Purpose|
|---|---|
|lt|	Less than|
|le|	Less than or equal to|
|gt|	Greater than|
|ge|	Greater than or equal to|
|eq|	Equal to|
|ne|	Not Equal to|

In [33]:
a = torch.randn((3,4))
print("The original tensor is \n {}".format(a))

print("="*30)
print("The comparison between a tensor and a single value.\n")
b = torch.lt(a, 0.5)
print("The element is less than 0.5 \n {}".format(b))

print("="*30)
c = torch.randn((3, 4))
print("The comparison between two tensors.\n")
d = torch.gt(a, c)
print("The comparison result between tesnor a and c \n {}".format(d))

The original tensor is 
 tensor([[ 2.3482,  0.1805, -0.5357,  1.2000],
        [-0.6827, -0.1046, -0.9332, -0.8011],
        [-0.1352,  0.0627,  0.9978, -1.1855]])
The comparison between a tensor and a single value.

The element is less than 0.5 
 tensor([[False,  True,  True, False],
        [ True,  True,  True,  True],
        [ True,  True, False,  True]])
The comparison between two tensors.

The comparison result between tesnor a and c 
 tensor([[ True, False,  True,  True],
        [ True, False, False,  True],
        [False,  True,  True, False]])


## Matrix Vector Multiplication

### 1. Matrix multiplication with vectors

Let us first see how we can multiply a matrix with a vector. **PyTorch** provides the <font color='red'>``</font>mv() function for this purpose.

We can use <font color='red'>`mv()`</font> in two ways. <font color='red'>`mv()`</font> could be called from a tensor, or just call it from <font color='red'>`torch.mv()`</font>. The first parameter for <font color='red'>`torch.mv()`</font> is a matrix.

In [34]:
mat = torch.ones((2, 4))
print("The matrix is \n{}".format(mat))

print("="*30)
vec = torch.tensor([1, 2, 3, 4], dtype=torch.float)
print("The vector is \n{}".format(vec))

print("="*30)
result = mat.mv(vec)
print("The result is \n{}".format(result))

print("="*30)
result = torch.mv(mat, vec)
print("The result is \n{}".format(result))

The matrix is 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
The vector is 
tensor([1., 2., 3., 4.])
The result is 
tensor([10., 10.])
The result is 
tensor([10., 10.])


**Note**: The order of the matrix and vector is critical, otherwise, you may trigger the runtime error. The first argument of <font color='red'>`mv`</font> should be the matrix, the second should be the vector. For example, if the matrix is an (<font color='red'>`n×m`</font>) tensor, then the vector should be is a 1-D tensor of size <font color='red'>`m`</font>.

### 3. Matrix multiplication with matrices

<font color='red'>`mm()`</font> is used in PyTorch to multiply two matrices. Similar to <font color='red'>`mv()`</font>, we have two ways to call <font color='red'>`mm()`</font>.

In [35]:
mat1 = torch.ones((2, 4))
mat2 = torch.ones((4, 3))

result = torch.mm(mat1, mat2)
print("The result is \n {}".format(result))

print("="*30)
result = mat1.mm(mat2)
print("The result is \n {}".format(result))

The result is 
 tensor([[4., 4., 4.],
        [4., 4., 4.]])
The result is 
 tensor([[4., 4., 4.],
        [4., 4., 4.]])


### 4. Dot product between vectors

The dot product is the sum of the products of the corresponding element of the two tensors. <font color='red'>`dot()`</font> is the function for this purpose.

We can use <font color='red'>`dot()`</font> in two ways. <font color='red'>`dot()`</font> could be called from a 1D tensor, or just call it from <font color='red'>`torch.dot()`</font>, which requires two **1D** tensors.

In [37]:
vec1 = torch.tensor([1, 2, 3, 4])
vec2 = torch.tensor([2, 3, 4, 5])

result = vec1.dot(vec2)
print("The result is \n {}".format(result))

print("="*30)
result = torch.dot(vec1, vec2)
print("The result is \n {}".format(result))

The result is 
 40
The result is 
 40


## Saving and loading tensors

### 1. Saving a single tensor

Sometimes, we want to dump a tensor to the disk for future use immediately after an operation. It could save a lot of time in scenarios where the processing takes too long and we don’t want to go through the whole process again.

**PyTorch** provides <font color='red'>`torch.save`</font> to save objects to a file-like object. In this lesson, we only save the object to a file. The first parameter is the object we want to save, in this example, it’s a tensor. In this example, the second parameter is a file path

In [38]:
a = torch.tensor([1, 2, 3])
torch.save(a, "./tensor.pt")

### 2. Loading tensors from a file

In the previous section, we learned how to dump a tensor into a local file. Now we look loading values into a tensor from a given file. It’s quite simple, just use the <font color='red'>`load()`</font> function and specify the file path as an argument. The function would return a tensor which can be copied into a variable, as shown below.

In [39]:
b = torch.load("./tensor.pt")
print("The tensor b is {}".format(b))

The tensor b is tensor([1, 2, 3])


### 3. Saving multiple tensors

There are many methods to save multiple objects to a local file. In this lesson, we use the simplest way to do it. We use a native Python map to store the objects and dump them with <font color='red'>`torch.save`</font>.

In [40]:
# m is a key-value structure to store variables.
# In this example, "t1" is the key, and tensor([1, 2, 3]) is the value.
m = {}
m["t1"] = torch.tensor([1, 2, 3])
m["t2"] = torch.tensor([2, 4, 6])
torch.save(m, "./m_tensor.pt")

m2 = torch.load("./m_tensor.pt")
print("The tensor map is {}".format(m2))

The tensor map is {'t1': tensor([1, 2, 3]), 't2': tensor([2, 4, 6])}


## Moving to GPU

One of the major advantages of PyTorch is its robust acceleration on CUDA-compatible Nvidia GPUs. ("CUDA" stands for *Compute Unified Device Architecture*, which is Nvidia's platform for parallel computing.) So far, everything we've done has been on CPU. How do we move to the faster hardware?

First, we should check whether a GPU is available, with the <font color='red'>`is_available()`</font> method.

**Note: If you do not have a CUDA-compatible GPU and CUDA drivers installed, the executable cells in this section will not execute any GPU-related code.**

In [41]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


Once we've determined that one or more GPUs is available, we need to put our data someplace where the GPU can see it. Your CPU does computation on data in your computer's RAM. Your GPU has dedicated memory attached to it. Whenever you want to perform a computation on a device, you must move *all* the data needed for that computation to memory accessible by that device. (Colloquially, "moving the data to memory accessible by the GPU" is shorted to, "moving the data to the GPU".)

There are multiple ways to get your data onto your target device. You may do it at creation time:

In [42]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


By default, new tensors are created on the CPU, so we have to specify when we want to create our tensor on the GPU with the optional <font color='red'>`device`</font> argument. You can see when we print the new tensor, PyTorch informs us which device it's on (if it's not on CPU).

You can query the number of GPUs with <font color='red'>`torch.cuda.device_count()`</font>. If you have more than one GPU, you can specify them by index: <font color='red'>`device='cuda:0'`</font>, <font color='red'>`device='cuda:1'`</font>, etc.

As a coding practice, specifying our devices everywhere with string constants is pretty fragile. In an ideal world, your code would perform robustly whether you're on CPU or GPU hardware. You can do this by creating a device handle that can be passed to your tensors instead of a string:

In [43]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.1986, 0.1779],
        [0.6366, 0.2301]])


### 1. Casting into different device type

If you have an existing tensor living on one device, you can move it to another with the <font color='red'>`to()`</font> method. The following line of code creates a tensor on CPU, and moves it to whichever device you specify.

If you have only one GPU, you can use the code below to get the GPU ID and cast it. If you have multiple GPUs, then you can use <font color='red'>`cuda:0`</font>, <font color='red'>`cuda:1`</font>, or <font color='red'>`cuda:2`</font> to get a different GPU.

In [44]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
a = torch.tensor([1, 2, 3])
c = a.to(device)

**Note**: It is important to know that in order to do computation involving two or more tensors, *all of the tensors must be on the same device*.

### 2. Checking if the tensor is on GPU

<font color='red'>`is_cuda`</font> is an attribute of a tensor. It is true if the tensor is stored on the GPU. Otherwise, it will be set to false.

#### Getting the device
device is an attribute of a tensor. It contains the information of the device being used by the tensor.

In [45]:
a = torch.randn((2, 3, 4), dtype=torch.float)
print("The GPU is {}.\n".format(a.is_cuda))
print("The device is {}.".format(a.device))

The GPU is False.

The device is cpu.


## And that's it for today!